### ISSUE TITLE
Quaternion Module Not found

### ISSUE THREAD

**Issue by NathanaelOliver** [softsys4ai/Multi-Sense-Rescuer#1]
@kksinghal, 
We are trying to replicate the results of this project, however, when we follow the instructions in the readme to setup the habitat-sim by running
`python setup.py install --headless --audio --with-cuda`
Anaconda says there is no module found Quaternion.

I have attached an image of the error.
[https://emailsc-my.sharepoint.com/:i:/g/personal/no2_email_sc_edu/EVUDNIxmMuFFhdCidW4EsTQBXOXYk-oQxVR86mc9HkWiRg?e=QhiyCV](url)

How do I resolve this?

**Comment by kksinghal** [comment]
Please see [this](https://stackoverflow.com/questions/56297527/how-to-fix-no-module-named-quaternion-in-python). Let me know if it works. I remember encountering this myself and installing numpy-quaternion worked.

**Comment by NathanaelOliver** [comment]
Thank you this fixed the issue. We are having some other issues just getting the code to run with the packages. Would you be available sometime in the next week to help us get the code set up?

**Comment by kksinghal** [comment]
Please share the steps taken so far and the error you got.

You will find most of the issues already addressed at Github issues of [soundspaces](https://github.com/facebookresearch/sound-spaces) and [habitat-sim](https://github.com/facebookresearch/habitat-sim/).

Since I built upon an existing codebase, I won't be of much help regarding package issues since most of the issues I also faced depended on the system configuration, so I suggest searching for it on the web. If you still have difficulty, feel free to post your error since I might be able to help you if I had encountered it myself. Here is also one good post for [installation](https://github.com/facebookresearch/sound-spaces/issues/80#issuecomment-1195121562).
